### PR TITLE
hashCode() fix

### PR DESCRIPTION
**Pull request by rfelgent**
IoC-ecosystem like Spring keep track of the beans to manage in a map or collection. A lot of implementations of collection/map use "hashCode()" of item to store. This causes trouble with the WebResourceFactory, as it throws a "UnsupportedOperationException" saying that its missing a @Path on the method name "hashCode()".

The method "toString()" is already excluded by the proxy and I would like to add the "hashCode()" method.

### CODE REVIEW

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Hi Rfelgent, 

many thanks for your contribution. 

Before we can review and potentially merge your pull request, we need you to sign [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html). Please note, that it takes a while until the OCA is officially approved and listed on the page linked above (which is a relevant list for us).

Also to have the things nicely organised, every pull request should have a issue opened in our [bugtracker](https://java.net/jira/browse/JERSEY). And it is a good practice to place mutually links from github to JIRA and vice versa. 

More information about contributing to Jersey: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code

Thanks,
Adam

**Comment by AdamLindenthal** [comment]
Hi Rfelgent, 

are yo going to sign & send the OCA? Or have you already done so?

Thanks,
Adam

**Comment by sassrobi** [comment]
@rfelgent it would be nice if you sign and send that OCA. We are waiting for this patch too :)

**Comment by mkopylec** [comment]
I need this patch too

**Comment by rfelgent** [comment]
Hello people,

sorry for the late response. 
I will send the OCA within next days.

**Comment by Zenedith** [comment]
Any news?

**Comment by Zenedith** [comment]
@rfelgent Are you alive? Please, send the OCA and make the jersey "great again"

**Comment by bushee** [comment]
@rfelgent Any news here? I need this patch badly - I've stumbled upon this problem 2 times already, rendering WebResourceFactory completely unusable in my spring app :(

**Comment by bushee** [comment]
C'mon guys, this is getting ridiculous... you can't get yourselves to review such trivial change in, like, 1.5 years?

**Comment by rfelgent** [comment]
I am alive and I am resending for a a 3rd time the OCA to: oracle-ca_us@oracle.com

Personally, I do not understand why this projects requires such "signing contract stuff". really unusual/weired for open source software ....

**Comment by Zenedith** [comment]
Latest news: this patch is not needed in latest spring boot version

**Comment by leonard84** [comment]
@Zenedith that is good however this should be fixed anyway. 

@rfelgent I also submitted my OCA in December and haven't heard back since, kinda disappointing if they require a CLA then they should handle the applications in a timely manner.

**Comment by shrykull** [comment]
@Zenedith I guess you mean version 2.0.0.SNAPSHOT? I tried 1.4.3.RELEASE and 1.5.0.RC1 and kept getting UnsupportedOperationException. However, i don't want to rely on snapshot dependencies so i stopped my little experiment.

**Comment by evanova** [comment]
@Zenedith : I can confirm this is not fixed with Spring 1.4.3 which is the current release. Can you specify which version you mean?

Seriously, this OCA paperwork requirement for a 1-line patch is beyond unreasonable.

**Comment by wadechandler** [comment]
I have put up https://github.com/jersey/jersey/pull/262, so hopefully that can be merged in and reviewed. I have been on the OCA list for years now.

**Comment by pavelbucek** [comment]
replaced by https://github.com/jersey/jersey/pull/262

**Pull request closed without merging**
