### PR TITLE
added @Priority handling to exception mappers; resolves JERSEY-2437;

### PR DESCRIPTION
**Pull request by sdaschner**
This adds handling of `@Priority` annotations on `ExceptionMapper`s as issued in JERSEY-2437 and JAX_RS_SPEC-532.

### CODE REVIEW

**Comment by pavelbucek** [comment]
Existing tests don't pass and there are no added tests.

Don't get me wrong, I appreciate the effort, but if you just have an idea about how something could be solved, please add them as a comment to a jira issue.

**Comment by sdaschner** [comment]
Yes, I know, sorry for that. The tests didn't run locally on my machine even before the commit, so I couldn't verify the changes :/

**Comment by sdaschner** [comment]
Is there some extra effort required to run the (integration) tests locally? I would be happy to contribute that feature properly, but without executing tests it's a little bit hard :-)

**Comment by pavelbucek** [comment]
no, you should be able to execute "mvn clean install" on freshly downloaded sources.

Anyway, don't mind this issue any more, I'll take care of it (re-evaluating pull requests would most likely consume more time than doing the implementation.. if I'll be able to make it backwards compatible).

**Comment by sdaschner** [comment]
Ok, yes `mvn clean install` from scratch didn't work last time. Anyway, sorry again.

**Comment by bric3** [comment]
@pavelbucek any news on this ?

**Comment by pavelbucek** [comment]
@bric3 not sure what you mean - this feature is included in JAX-RS 2.1 and Jersey 2.26. (actually, we did make all provider ordering respect @Priority annotation..)

**Comment by chkal** [comment]
@bric3 If you tried to use `@Priority` on exception mappers and it didn't work, have a look at #3670 which I created some time ago. The issue is about param converters, but I'm pretty sure exception mappers are also affected.

**Comment by bric3** [comment]
@pavelbucek I didn't know it was included in 2.26, and I missed the new section §4.1.3 of the 2.1 specification (the migrated issues on github are not assigned to any milestone) 

@chkal Interesting issue, it may be relevant for me.

**Pull request closed without merging**
