### PR TITLE
ApacheConnector: Set timeouts on per-request basis

### PR DESCRIPTION
**Pull request by rohansingh**
This better matches the behavior of the HttpUrlConnector.

Fixes: https://java.net/jira/browse/JERSEY-2698.

### CODE REVIEW

**Comment by AdamLindenthal** [comment]
Hi Rohan, any news regarding the OCA? I still do not see nor you neither your company on the list. Do you know what is blocking the progress? Is the problem on our side and should we ask for the status? Thanks.

**Comment by rohansingh** [comment]
Hey Adam, I originally sent in the OCA on behalf of Spotify on December 2nd, and then followed up on December 8, but have yet to receive a response.

The address I'm sending to is oracle-ca_us@oracle.com. Are you aware of any better way to submit this?

**Comment by AdamLindenthal** [comment]
Hi Rohan, 
just checked with the guy who takes care of the OCA process and your OCA is indeed being processed. Your case is a bit more specific, so there is some additional confirmation required on our side that slows things down a bit - sorry for that.

**Comment by rohansingh** [comment]
Great, thanks for looking into it!

**Comment by mattbishop** [comment]
Rohan this PR has merge conflicts. Will you be able to refresh it?

**Comment by rohansingh** [comment]
Sure, I'll put it on my to-do list.

**Comment by mgajdos** [comment]
LGTM, can be merged when merge conflicts are resolved.

**Comment by AdamLindenthal** [comment]
Hi Rohan, just a kindly reminder :-) I know that we are were kind of slow, so we are not in position to remind you, but I'll do it anyway - I am awaiting that lucky day when this is finally merged :-)

**Comment by mpotociar** [comment]
Closing the PR due to inactivity of contributor. Will fix the issue via internal commit instead.

**Comment by rohansingh** [comment]
Apologies folks. Have been swamped lately. If you're fixing this via another commit, totally fine with me. Otherwise I can try to get to it today.

**Comment by mpotociar** [comment]
I certainly do not want to take the contribution away from you. So if you can update the patch today, we can wait for it.

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by rohansingh** [comment]
Looks like it failed due to copyright year again? It's expecting 2014 instead of 2015 though?

**Comment by AdamLindenthal** [comment]
I guess this is caused by the original commit date in October last year and it kept its date even after rebase. Actually I am not sure what happens after I merge it, but in the bad scenario I will "touch" the files somehow in order to give it the correct commit date. I'll try to merge it tomorrow when I will be able to check, that our checks didn't start to fail.

**Comment by AdamLindenthal** [comment]
Just merged the commit, if our internal checks will start to fail on copyright headers, I will create one more commit to fix that. 
Thank you for contributing!
Adam

**Pull request merged**
