### PR TITLE
Fix JERSEY-2865

### PR DESCRIPTION
**Pull request by panghy**
Synchronization should be on the ChunkedOutput class and not on the Callable.

### CODE REVIEW

**Comment by mgajdos** [comment]
Hi @panghy, 
thanks for your contribution. 

Before we can review your pull request, we need you to sign [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html).

More information about contributing to Jersey: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code…

Regards,
Michal

**Comment by panghy** [comment]
Attached.

Clement

**Comment by panghy** [comment]
I don't think the attachment worked. To whom should I email the agreement to?

**Comment by mgajdos** [comment]
It's mentioned on the [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) page: oracle-ca_us [at] oracle [dot] com.

**Comment by mgajdos** [comment]
If possible – can you also provide a test? Just to make sure this won't happen again.

**Comment by panghy** [comment]
Hm, testing this might prove difficult since it basically only happens when there's concurrent writes.

OCA sent to the email address given.

**Comment by mgajdos** [comment]
This change can be merged once the OCA is confirmed.

**Comment by mgajdos** [comment]
Jenkins, test this patch.

**Comment by panghy** [comment]
Just got this email:

David Delabassee david.delabassee@oracle.com via bounce.secureserver.net 
Jun 12 (4 days ago)

to Clement, Marek 
Clement,

Your OCA has been reviewed and approved.
Thanks for your support!

**Comment by mgajdos** [comment]
Thank you, @panghy, for your contribution.

**Pull request merged**
