### PR TITLE
JERSEY-2928: declarative-linking: @BeanParam linking support

### PR DESCRIPTION
**Pull request by sfuhrm**
The declarative-linking feature has no support for the [@BeanParam](https://jax-rs-spec.java.net/nonav/2.0-SNAPSHOT/apidocs/javax/ws/rs/BeanParam.html) annotation.
This pull request changes it at least for @QueryParams in the beans' fields and setters.

See also https://java.net/jira/browse/JERSEY-2928

### CODE REVIEW

**Comment by sfuhrm** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Stephan, Jenkins won't listen to you. I'll re-trigger the build.

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by stepanv** [comment]
Stephan, thanks for your PR. I commited it slightly corrected, squashed and rebased. I hope that's ok for you. See https://github.com/jersey/jersey/tree/e57086311c844554ed3cd24ba24a26330c53d501.

**Pull request closed without merging**
