### PR TITLE
JERSEY-2892: Fixed EntityFiltering when repeating classes in object gr…

### PR DESCRIPTION
**Pull request by stepanv**
…aph were incorrectly filtered out.

This pull request is here so that our VIP contributor Michal Gajdos can kindly review it.

### CODE REVIEW

**Comment by stepanv** [comment]
Jenkins, please re-test this patch.

**Comment by mgajdos** [comment]
+2, LGTM.

**Comment by AdamLindenthal** [comment]
Jenkins, please re-test this patch.

**Comment by pavelbucek** [comment]
Jenkins, please re-test this patch.

**Comment by stepanv** [comment]
Pushed through Gerrit.

**Pull request closed without merging**
