### PR TITLE
JERSEY-2852: ClientResponse does not close ClosableHttpResponse

### PR DESCRIPTION
**Pull request by marcuslinke**
This fixes https://java.net/jira/browse/JERSEY-2852 

Please review and merge. Thanks!

### CODE REVIEW

**Comment by mgajdos** [comment]
Hi @marcuslinke, 
thanks for your contribution. 

Before we can review your pull request, we need you to sign [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html).

More information about contributing to Jersey: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code…

Also provide some tests that would cover new code and add copyright header to the new file. Thanks.

Regards,
Michal

**Comment by AdamLindenthal** [comment]
Hi Marcus, 
have you noticed Michal's reponse? Any follow-up? I mean - are you still planning to continue the work on this?

Thanks, 
Adam

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Hi Marcus, will you sign and send the OCA? Or have you already done so?
Please, let us know. Also, we will need you to create a unit test for your change.

Thanks,
Adam

**Comment by AdamLindenthal** [comment]
Hi Marcus, 

I am sorry, but since you didn't respond since may and didn't sign the OCA, I am closing the PR. 
Once you have more time to finish this, feel free to re-try.

Regards,
Adam

**Comment by KostyaSha** [comment]
Fixed via https://github.com/jersey/jersey/commit/b5b9fb6ac8c77cfe172dbab490d5bdfaaff44388

**Pull request closed without merging**
