### PR TITLE
typo in jax-resources.xml fixed, repeated from

### PR DESCRIPTION
**Pull request by smirzai**
Fixed a small typo in jax-resources.xml. Repeated "from"

### CODE REVIEW

**Comment by AdamLindenthal** [comment]
Hi Saeid, 

thanks for creating the pull request. On first contribution, we need everyone to sign the [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) (OCA). 

After you send it in, it usually takes several weeks until the OCA is processed, approved and listed on the page linked above (which is relevant for us). This has to be done the first time only, future pull requests can be reviewed right off. 

As this is a very small change, please consider if you are willing to go through the process. If you plan to contribute more in the future, than it makes 100% sense, otherwise it's up to you. Just please let us know, should you have decided not to do it, we would fix the typo via an internal commit.

Regards,
Adam

**Comment by smirzai** [comment]
Hi Adam,
nice to hear from you.
I read about the OCA, but I did not think it would be required for such a
small correction.
I would like to extend my open source experiences and we are using jersey
in the company, so it makes sense for me to sign the agreement.


kind regards,
Saeid

**Comment by AdamLindenthal** [comment]
Nice, glad to hear that. Please be prepared for some waiting time (few weeks, as written above) and after you receive a confirmation, feel free to ping us here (as we do usually not get any notifications and have to occasionally check the OCA page).

Regards,
Adam

**Comment by smirzai** [comment]
My OCA request is just accepted.

**Pull request merged**
