### PR TITLE
Add support for nested generics to ConfigurableMoxyJsonProvider

### PR DESCRIPTION
**Pull request by lasselasse**
This change fixes a known Moxy issue which has unfortunately been unresolved since July 2013: https://bugs.eclipse.org/bugs/show_bug.cgi?id=413809

### CODE REVIEW

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Hi Lasse, 
many thanks for your contribution. 

Before we can review your pull request, we need you to sign [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html). 
Please note, that it takes a while until the OCA is officially approved and listed on the page linked above (which is a relevant list for us).

Also, I know, that there is already a moxy issue opened, but we tend to apply a rule, that every pull request should have an issue opened in *our* [bugtracker](https://java.net/jira/browse/JERSEY), ideally mutually linked from github to JIRA and vice versa.

More information about contributing to Jersey: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code

Thanks,
Adam

**Comment by lasselasse** [comment]
I have just submitted the signed OCA and created a Jersey issue: https://java.net/jira/browse/JERSEY-2758

**Comment by shamoh** [comment]
Thanks a lot.

May you also add simple unit test to https://github.com/jersey/jersey/blob/master/tests/e2e/src/test/java/org/glassfish/jersey/tests/e2e/entity/JsonMoxyTest.java class to proof the fix? Thanks.

**Comment by shamoh** [comment]
Signed OCA has been confirmed, thanks.
Dear Universe, add to whitelist Mr. Lasse.

**Comment by mgajdos** [comment]
I am going to merge this pull request but it'll be reverted once MOXy 2.6 with the "real" fix is released and integrated into Jersey.

**Comment by lasselasse** [comment]
Thanks @mgajdos I just saw that the issue has been addressed in MOXy just now, which of course will be the best solution onc eit has been realeased.

**Pull request merged**
