### PR TITLE
Added functionality to optionally extract provided Content-Type in Header

### PR DESCRIPTION
**Pull request by elmar-schwarz**
We need a mechanism to invoke a dynamic client proxy with a specific content-type which is not necessarily identical with the first value in the “@Consumes” annotation. In analogy, providing a custom “Accept”-Header is already working.

The provided piece of code solves the problem for us. It could be considerable to try to match the header-value against the list of consumed content-types of the actual service, but for several reasons we decided to use the provided header without validating it. We left it to the service to make the final decision to accept the content-type or not.

### CODE REVIEW

**Comment by AdamLindenthal** [comment]
Hi Elmar,
many thanks for your contribution. 

Before we can review your pull request, we need you to sign [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html). Please note, that it takes a while until the OCA is officially approved and listed on the page linked above (which is a relevant list for us).

Also to have the things nicely organised, every pull request should have a issue opened in our [bugtracker](https://java.net/jira/browse/JERSEY). And it is a good practice to place mutually links from github to JIRA and vice versa.

More information about contributing to Jersey: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code

Thanks,
Adam

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Just quickly checked which files are affected and without really reviewing the code itself, there is a minor issue with the copyright header. When a file is touched the first time the given year, the copyright header needs to be updated, otherwise our checks will fail.

Could you please change the year range from `2012-2014` to `2012-2015` and re-commit (either new commit or amend).

Thanks!

**Comment by elmar-schwarz** [comment]
Should implement functionality as requested in https://java.net/jira/browse/JERSEY-2757.

**Comment by elmar-schwarz** [comment]
Signed OCA submitted to 'oracle-ca_us@oracle.com'.

**Comment by AdamLindenthal** [comment]
Nice, thanks.

**Comment by elmar-schwarz** [comment]
OCA officially accepted: http://www.oracle.com/technetwork/community/oca-486395.html#s.

**Comment by shamoh** [comment]
Signed OCA has been confirmed, thanks.
Dear Universe, add to whitelist Mr. Elmar Schwartz.

**Comment by elmar-schwarz** [comment]
Schwarz ;-)

**Comment by mgajdos** [comment]
Hi Elmar,

please, change copyright years in modified test classes. It should read `2012-2015` for all of them. I'll run the verification then and when it passes I'll merge the change.

Michal

**Comment by elmar-schwarz** [comment]
Hi Michal,

I made the necessary changes.

Regards, Elmar

**Comment by mgajdos** [comment]
Jenkins, please test this patch.

**Comment by mgajdos** [comment]
Verified manually.

**Comment by mgajdos** [comment]
@elmar-schwarz Thank you for your contribution. The change will be released with Jersey 2.17.

**Pull request merged**
