### PR TITLE
JERSEY-2835

### PR DESCRIPTION
**Pull request by khaing211**
Add new ApacheClientProperties.DISABLE_AUTOMATIC_RETRIES flag

### CODE REVIEW

**Comment by mgajdos** [comment]
Hi @khaing211 , 
thanks for your contribution. 

Before we can review your pull request, we need you to sign [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html).

More information about contributing to Jersey: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code…

Regards,
Michal

**Comment by mgajdos** [comment]
Can you also provide a test for your change?

**Comment by khaing211** [comment]
Hi Michal,

I have submitted OCA to oracle-ca_us@oracle.com. Also, I add DisableAutomaticRetryTest.

Regards,
Khai

**Comment by AdamLindenthal** [comment]
Hi Khai, 

it's been a while since you've sent in the OCA, can you see your name listed on the list at http://www.oracle.com/technetwork/community/oca-486395.html ?

Surprisingly, I don't, but I am not sure if your github profile name is your full real name, so please check and let me know. I would expect the OCA to be processed at least a month ago or so.

Thanks,
Adam

**Comment by AdamLindenthal** [comment]
Hi Khai, 

it's been quite a while since we have heard from you the last time. I still don't see your OCA.
I have to close this for now.

If you feel like having time to take this to the finish, please feel free to request re-opening or create a new PR along with the valid OCA.

Regards,
Adam

**Comment by fredericBregier** [comment]
Could you find a way to include this MR or redoing it since for me this improvement is quite mandatory too ? 

I know the issue on OCA, but this is quite frustrating this is missing while the patch is doing the job.

Currently we do have the very same kind of patch to handle this but forking the current ApacheConnector in order to support it properly.

**Pull request closed without merging**
