### PR TITLE
JERSEY-2871: use same prefix id for request and its response

### PR DESCRIPTION
**Pull request by efonsell**

### CODE REVIEW

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Hi Edvard, thanks for your contribution. 

Before we can review your pull request, we need you to sign [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html). Please note, that it takes a while until the OCA is officially approved and listed on the page linked above (which is a relevant list for us).

As you already opened the JIRA issue as well, I guess you know about the process, so just for reference, - should you need some more information about contributing to Jersey, please visit: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code

Thanks,
Adam

**Comment by efonsell** [comment]
Hi Adam,
I just signed and sent the OCA. Waiting for the approval...
br, Edvard

**Comment by AdamLindenthal** [comment]
Thanks, Edvard! 
That was very fast. Unfortunately, I cannot promise you the same speed with the OCA approval :-) It usually takes several weeks, so patience will be your best friend... 
If you notice, that you appeared on the list or you will be notified, don't hesitate to let us know here. 

Cheers,
Adam

**Comment by efonsell** [comment]
Ok!

**Comment by mgajdos** [comment]
Thank you, @efonsell, for your contribution.

**Pull request merged**
