### PR TITLE
Adding Guice integration example.

### PR DESCRIPTION
**Pull request by TheIndifferent**
Was not impressed by rather big and not-simplifying integration libraries, so spent some time to understand the internals of Jersey and was able to implement cleaner and transparent integration to serve Jersey endpoints with Guice servlet module. Hope this will be useful for wider audience.

### CODE REVIEW

**Comment by AdamLindenthal** [comment]
Hi Stanislav,
thank you for your contribution. Could you please also open new issue in our [JIRA](https://java.net/jira/browse/JERSEY). and eventually place mutuall links from github to JIRA and vice versa.
For more info regarding contributions, you can visit: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code

Regards,
Adam

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by TheIndifferent** [comment]
Adam,
Sorry for such a late reponse. Created the Jira issue, but not sure where to put it:
https://java.net/jira/browse/JERSEY-2766

**Comment by AdamLindenthal** [comment]
Hi, thank you. 
To answer the question where to put the link - best way is to put the JIRA 'code' into the name of the pull request, such as *JERSEY-2766 - Adding Guice integration example* or something similar and/or to put the link in the description. 

But that's just what is optimal. The way you did it is also fully sufficient. We just need to have the reference somewhere, link in a comment is just enough.

Anyway, we will try to get to your patch back soon.

Cheers,
Adam

**Comment by japod** [comment]
Hi Stanislav,

Thanks for working out the example and for your patience when waiting for the review!

There are two things missing in the pull request:

1. Jersey/Guice integration works only one way in the example application
2. there is no test

ad 1) to ensure full bi-directional integration, you should be able to inject JAX-RS stuff
         into Guice provided components. E.g. 

```java
@Path("/hello")
public class HelloEndpoint {

  @Context UriInfo uriInfo;
  @QueryParam("q") String q;
  ...
```

ad 2) the test should be processed as part of the build to ensure no regressions occur

Would you be willing/able to update your pull request to address the above feedback?

~Jakub

P.S. There is another rather formal and minor thing: wrong year in the copyright headers.
Please consider fixing that as well.

**Comment by TheIndifferent** [comment]
Hi Jakub,

Thanx for the review. Sure, I think I'll be able to update the pull request in couple of days.

**Comment by AdamLindenthal** [comment]
Hi, Stanislav - just a kindly reminder, do you thing you will be able to update according to Jakub's comments anytime soon?

Thanks a lot,
Adam

**Comment by TheIndifferent** [comment]
Hi Adam,

Unfortunately it appeared to be more complicated than I expected, plus I've found another issue with it. Probably it would be better to reject this pull request at the moment, but I hope I will return with proper solution in couple of weeks (depending on how much time I'll have), and will create new pull request then.

**Comment by AdamLindenthal** [comment]
Understood. Thanks for quick response. Since you already have a valid OCA, the process will be much smoother next time. 
I will close the pull request for now, so that we do not keep reminding you and as you said, create a new one whenever you are done. 
I will also close the "underlying" JIRA issue, just let us know when it is time to reopen it (or feel free to create a new one).
Thank you so far!

Adam

**Pull request closed without merging**
