### PR TITLE
Patch https clientserver grizzly

### PR DESCRIPTION
**Pull request by ophers**
This is a patch for [JERSEY-2836](https://java.net/jira/browse/JERSEY-2836)

### CODE REVIEW

**Comment by ophers** [comment]
Btw, I've just signed the Oracle Contributor Agreement and emailed it to oracle-ca_us [at] oracle [dot] com.

**Comment by AdamLindenthal** [comment]
Hi Ophers, thanks for contributing. The OCA processing will take a while (but has to be done the first time only), so please be patient.

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Hi again, I just triggered the verification build. Please don't panic if it fails (it most likely will). There is a problem, that does not relate to your patch.

**Comment by AdamLindenthal** [comment]
Hi Ophers, I just realized, that you have not changed the copyright headers. If I merged your PR now, it would cause our future builds to fail until this is fixed.
Every time you touch a file, you need to check, that the copyright header contains the correct year.
In this case, please change `Copyright (c) 2010-2012` to `Copyright (c) 2010-2015`.

Thanks,
Adam

**Comment by ophers** [comment]
OK.

**Comment by AdamLindenthal** [comment]
Thanks, that looks good. Let's go through the (hopefully) last verification iteration. Overall I'm fine with the patch, so if it passes, I guess it can be merged.

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Hi, the verification failed, but the problem is not related to your patch. It is a known problem, that should be already resolved. Hence, merging.

Thanks for your contribution!

**Pull request merged**
