### PR TITLE
JERSEY-2982: AsyncResponse support for the Simple HTTP container

### PR DESCRIPTION
**Pull request by ngallagher**
For contains the following:

1) Support for the AsyncResponse
2) Upgraded to use Simple 6.0.1
3) Added very low level I/O trace analyzer

FYI - Some checkstyle warnings arose when I did a build, not sure what the style guide is though?

### CODE REVIEW

**Comment by ngallagher** [comment]
Can this patch be merged? I am happy to make any additional changes needed. The asynchronous HTTP container this is built upon is maintained by me at:

https://github.com/ngallagher/simpleframework

**Comment by ngallagher** [comment]
Checkstyle errors fixed

**Comment by AdamLindenthal** [comment]
Hi Niall,

many thanks for your contribution. 

Before we can review your pull request, we need you to sign [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html).

More information about contributing to Jersey: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code

Regards,
Adam

**Comment by ngallagher** [comment]
I have signed the OCA many times before, however I have also checked it in as I could not find anywhere else to upload it.

https://github.com/ngallagher/jersey/blob/master/OCA.pdf

**Comment by ngallagher** [comment]
Why was this closed?

**Comment by ngallagher** [comment]
The OCA has been signed and mailed to oracle-ca_us at oracle.com.

**Comment by pavelbucek** [comment]
I have squashed your commits, fixed formatting and other stuff and merged into master and 2.x branches.

Thanks for out contribution!

**Pull request closed without merging**
