### PR TITLE
Traverse maps during field processing

### PR DESCRIPTION
**Pull request by glucas**
This fixes JERSEY-3088.

### CODE REVIEW

**Comment by pavelbucek** [comment]
Hi Glucas,

thanks for the pull request. You'll need to sign OCA - unless you do that, we cannot consider merging that into Jersey codebase. Please see http://www.oracle.com/technetwork/community/oca-486395.html for more details.

Also, each fix needs to contain the testcase - we cannot be sure that the fix is still valid if there is none. Can you please update the change?

Thanks,
Pavel

**Comment by glucas** [comment]
Thanks, I'll review the agreement and look at adding a test case.

**Comment by glucas** [comment]
I know this isn't the place, but if anyone can comment on the OCA process I'd appreciate it. I submitted the form weeks ago and have seen no response (automated or otherwise) so no idea if it has been rejected, not received, etc.

**Comment by pavelbucek** [comment]
Can you please send me details about your OCA agreement (when did you sent it etc) to pavel.bucek (at) oracle.com?

**Comment by delabassee** [comment]
OCA approved, approval notification sent on July 14

**Comment by pavelbucek** [comment]
Hi David, thanks for notification - we use label "OCA" to indicate that OCA for the pull request exists, so this particular pull request is fine in terms of the contributor agreement.

**Comment by glucas** [comment]
I've added test coverage as requested. (I may have done the wrong thing with updating my dev branch from master -- I can create a clean pull request if necessary.)

**Comment by pavelbucek** [comment]
@glucas if you could squash your changes into single commit and rebase it on top of 2.x branch, it would be best. (I believe you can do that and then force push to pull request branch, but if its easier to create new pull request, feel free to do that).

Thanks!

**Comment by glucas** [comment]
I submitted a pull request #234 for this, so closing this one. I branched off 2.x and fixed up the commits there.

**Pull request closed without merging**
