### PR TITLE
JERSEY-2085 Support nested Jars

### PR DESCRIPTION
**Pull request by alexleigh**
As requested, this is #30 rebased on top of latest Jersey master. It is a fix for https://java.net/jira/browse/JERSEY-2085, supporting nested Jars.

### CODE REVIEW

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Hi Alex, 

thank you for taking care of this contribution.

Before we can continue with review and hopefully merging the pull request, I'll have to ask and make it clear if we need the [OCA](http://www.oracle.com/technetwork/community/oca-486395.html) signed also from you or if the original contributor's (Manabu) one will be sufficient. 
I'm afraid it won't - as officially, you are now the contributor from our point of view.

I will let you know as soon as I know myself.

Regards
Adam

PS: If you plan to make some more contributions in the future, than don't wait for my answer and feel free to send the signed OCA copy anyway.

**Comment by AdamLindenthal** [comment]
Hi again,
unfortunately, my original thought was correct. We need also you to sign the [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) before we can work with your pull request (review and merge), regardless that the original contributor is already our official contributor.
It is a one-time-only action (you can than create as many pull requests as you like with it) and it takes usually several weeks, until it is officially listed on the page linked above, which is the relevant source for us. 
Regards,
Adam

**Comment by shamoh** [comment]
Just a kind reminder, @alexleigh may you sign Oracle Contributor Agreement? Thanks a lot.

**Comment by AdamLindenthal** [comment]
Hi Alex, are you still with us? 
We cannot merge this with no OCA signed. 
This unfortunately means that we will have to close this PR if you do not respond soon and confirm, that you are willing to send the signed copy of the agreement.

**Comment by alexleigh** [comment]
Sorry about the delay, I will send over the OCA before the end of this week.

**Comment by AdamLindenthal** [comment]
Thanks, Alex!

**Comment by shamoh** [comment]
This code does not work. There is another pull request 196 to fix same issue.

**Pull request closed without merging**
