### PR TITLE
Fix for Versioned Applications - https://java.net/jira/browse/JERSEY-2626

### PR DESCRIPTION
**Pull request by lprimak**
New pull request fixes checkstyle errors

### CODE REVIEW

**Comment by lprimak** [comment]
OCA is approved for me already

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Thanks Iprimak. We are a bit under load now, but we'll try to take a look at it soon.

**Comment by lprimak** [comment]
Looks like it's ready to be integrated.
Thank you!

**Comment by mgajdos** [comment]
Hi Lenny,

I know it's been a long time but would it be possible for you to create some integration tests that would verify it? An example of such a test can be seen here: https://github.com/jersey/jersey/tree/master/tests/integration/cdi-ejb-test-webapp

Otherwise it looks good.

Thanks,
Michal

**Comment by lprimak** [comment]
I can do that but I would hope that it wouldn't hold up the patch integration. 
I.e. I can commit to doing the tests but please don't wait for them to integrate the patch. 

Current situation is a fatal error and the patch could not possibly be any worse since its been tested for over a year. 

Thank you.

**Comment by mgajdos** [comment]
OK, we have a deal :-) Thank you for your contribution.

**Comment by lprimak** [comment]
I looked at the test example provided, but unfortunately, it doesn't apply to this scenario.
The failure scenario is only relevant in deployment of versioned apps to GlassFish
$ asadmin deploy -name myapp:1.0
I don't see how I can simulate that in the Jersey integration tests.
And since all other tests pass, there are assurances no regression snuck in.

Not sure what else I can do.

**Pull request merged**
