### PR TITLE
Petr Bouda has been exiled and become a contributor.

### PR DESCRIPTION
**Pull request by petrbouda**

### CODE REVIEW

**Comment by shamoh** [comment]
+1

**Comment by pavelbucek** [comment]
:->

**Comment by pavelbucek** [comment]
missing change in pom.xml + copyright year not updated ;-)

**Comment by delabassee** [comment]
OCA?

**Comment by pavelbucek** [comment]
@delabassee there are no code changes.

Petr is former member of Jersey team and the commit only removes his oracle email address from javadoc @author fields. I will need to fix the commit anyway, include copyright fixes and cleanup of pom.xml. I will reset the committer and the message, so the pull request won't be accepted but similar change will be done by me. hope that is ok ;)

**Pull request closed without merging**
