### PR TITLE
Jersey 2625

### PR DESCRIPTION
**Pull request by kingsfleet**
A fix for issue JERSEY-2625, basically JPA was adding in a whole load of extra fields, the only way to really deal with this was to exclude all transient fields as they are not marked otherwise.

Whilst I was in there I also excluded a few other common cases such as String and primitive types in order to make things that much quicker.

### CODE REVIEW

**Comment by kingsfleet** [comment]
Jenkins, please test this patch

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Hi Gerard, 
thank you for the patch.

Just to clarify - those Jenkins commands will only trigger the build if one of the defined group of Jersey developers writes it.

**Comment by AdamLindenthal** [comment]
Hi, the build failure does not seem to be related to this PR, hence re-triggering.

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by AdamLindenthal** [comment]
Hi, even if it won't fix the ailing build (which does not seem to be related to your patch), could you please rebase to the latest master? There was a problem with jdk8 build fixed recently... 

Many thanks,
Adam

**Comment by AdamLindenthal** [comment]
Verified manually, otherwise looks good to me. 
Well, maybe the message when the test fails could be a bit more conservative :-)

**Comment by kingsfleet** [comment]
Adam, fair comment - I have updated the failure message sorry about that.
Jenkins, you are dead to me.

**Comment by AdamLindenthal** [comment]
Gerard, many thanks. 
I hate to say that, but you've made a typo ("interator") when fixing that message... Normally I would merge it and create new internal commit to fix such a minor thing, but in this case - I would like to ask you to rebase to the latest jersey master, so you can fix that with the next commit. 

After this is done, I guess nothing prevents this PR from being merged.
Regards,
Adam

**Comment by kingsfleet** [comment]
Done, I hope. Sorry about that.

**Comment by AdamLindenthal** [comment]
Merged, thank you!

**Comment by AdamLindenthal** [comment]
Gerard, please don't get confused by the OCA label, it servers just for our overview and unification.

Cheers,
Adam

**Pull request merged**
