### PR TITLE
Fix bug causing hints to be printed as warnings.

### PR DESCRIPTION
**Pull request by bakksjo**
Seems like a copy-paste bug.

### CODE REVIEW

**Comment by bakksjo** [comment]
Ping, anyone? This is a fairly simple fix. Should be quick to verify.

**Comment by bakksjo** [comment]
Fix for issue https://java.net/jira/browse/JERSEY-3077

OCA sent.

**Comment by pavelbucek** [comment]
Hi,

we need to wait untile the OCA is processed - and visible on the main page (http://www.oracle.com/technetwork/community/oca-486395.html).

Regards,
Pavel

**Comment by bakksjo** [comment]
Looks like the OCA has gone through now.

**Comment by hakonhal** [comment]
Any update?

**Comment by AdamLindenthal** [comment]
Verified manually & merged. 
Thanks for your contribution.

**Pull request merged**
