### PR TITLE
2.6.x

### PR DESCRIPTION
**Pull request by billjohnking**
test

### CODE REVIEW

**Comment by AdamLindenthal** [comment]
Sorry, Bill, but I don't get why this is pushed here... 
Closing the PR.

**Comment by billjohnking** [comment]
Sorry, I don`t know how to use github, and might did something wrong.
Really sorry about that.

Best,

Bill

**Comment by AdamLindenthal** [comment]
No problem, I was just surprised a bit when I saw this :)
Have a nice day,
Adam

**Comment by billjohnking** [comment]
Thank you, sir. You too :)

Bill

**Pull request closed without merging**
