### PR TITLE
Update getting-started.xml

### PR DESCRIPTION
**Pull request by yeonhoyoon**
fix typo

### CODE REVIEW

**Comment by mgajdos** [comment]
Hi @yeonhoyoon, 
thanks for your contribution. Unfortunately even for a smaller fixes like this we need you to sign [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html).

More information about contributing to Jersey: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code…

Once you sign the OCA you'd become a Jersey/GlassFish contributor and you can provide other contributions without signing any more OCAs.

Regards,
Michal

**Comment by yeonhoyoon** [comment]
Hello @mgajdos,
I've signed the OCA and sent it to oracle-ca_us [at] oracle [dot] com 3 days ago, but I didn't get any response back. Could you check the submission?

**Comment by yeonhoyoon** [comment]
@mgajdos 
I've received an email stating that my OCA was approved.

**Comment by mgajdos** [comment]
@yeonhoyoon Great. Thank you for your contribution!

**Pull request merged**
