### PR TITLE
Fix ordering such that the request content is written after calling a…

### PR DESCRIPTION
**Pull request by azell**
…sync send.  Reference: https://java.net/jira/browse/JERSEY-2949

### CODE REVIEW

**Comment by AdamLindenthal** [comment]
Hi, thanks for creating the pull request. I didn't notify you regarding OCA with your previous pull request, as we were discussing the technical aspect, so sorry for not doing that earlier.

Before we can review your pull request, we need you to sign [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html).

More information about contributing to Jersey: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code

Thanks,
Adam

**Comment by AdamLindenthal** [comment]
Jenkins, please test this patch.

**Comment by azell** [comment]
I should have time to sign the OCA tomorrow.

**Comment by AdamLindenthal** [comment]
Hi, that's a good news. FYI, the verification build failed, but that should not be related to your patch, as soon as the problem is fixed, we will re-run the job.

Also, please take into account, that the OCA takes a while to be processed and approved (usually several weeks). In the meantime, it would be useful if you could provide at least one test that makes sure, that nobody accidentally reverts your change as a side effect of some other changes in the future.

Regards,
Adam

**Comment by AdamLindenthal** [comment]
Jenkins, please re-test this patch.

**Comment by azell** [comment]
I have emailed the signed OCA to Oracle.  I will work on a Jetty client unit test.

**Comment by AdamLindenthal** [comment]
Great, thanks. Please feel free to ping us once you get the confirmation, that the OCA is approved (we usually don't get notified automatically and have to check the OCA page from time to time explicitly).

Regards,
Adam

**Comment by azell** [comment]
I have been added to the OCA list, though they did manager to misspell my last name ("Adam Zeel - GlassFish Jersey").

**Comment by AdamLindenthal** [comment]
Ooops, sorry for that. Should I try to contact them to fix it or did you already reply?

**Comment by azell** [comment]
The web page has been updated, so we are good :).

**Comment by azell** [comment]
If the pull request is accepted and Jersey 3.0 is Java 8 minimum, then 3.0 can use a more recent version of Jetty such as 9.3.4.v20151007.

**Comment by mpotociar** [comment]
Hi, would it be possible to add a reproducer unit test that demonstrates the deadlock and the fix?

It is our rule that all bug fixes must be accompanied with a reproduced test unless the test is highly difficult or impractical to create.

**Comment by azell** [comment]
Hello,

The simplest test is to:

Verify that *jetty.version* is set to **9.1.1.v20140108** in pom.xml (current default).

```
cd connectors/jetty-connector
mvn test -Dtest=EntityTest
```

The test should pass.  Now set *jetty.version* to **9.2.13.v20150730** in the top-level pom.xml and run the above commands again.  The test will hang.  Apply my pull request and the test should again pass.

Is there a need for another test?

**Comment by azell** [comment]
Any update on this request?  Thanks!

**Comment by pavelbucek** [comment]
The commit has been merged as part of #205 and #204 . Thanks Azell for your contribution!

**Pull request closed without merging**
