### PR TITLE
Added Apache client property to allow application to specify a retry handler

### PR DESCRIPTION
**Pull request by agherardi**
Made ApacheConnector's HttpEntity repeatable. Added Apache client property to allow application to specify a retry handler

### CODE REVIEW

**Comment by agherardi** [comment]
OCA was approved

**Comment by agherardi** [comment]
Any updates? Thanks.

**Comment by pavelbucek** [comment]
What happens when the entity is an InputStream? That cannot be repeatable by design..

.. but I can see the benefit of your change - shouldn't the "repeatable" flag be something settable per-request?

**Comment by agherardi** [comment]
>>>> What happens when the entity is an InputStream?
Yes, that's a good point.

The application can work around the repeatability problem by turning on entity buffering. Therefore, I partially reverted my changes to ApacheConnector - I left the changes to allow the application to specify a retry handler. I also updated my unit-test to turn on entity buffering.

**Comment by agherardi** [comment]
Any updates? This pull request allows an application to specify a retry handler for the Apache connector, which I believe is a useful feature. Can it be merged?

**Comment by pavelbucek** [comment]
Can you please squash your commits into a single one and rebase to the latest commit?

**Comment by agherardi** [comment]
Done

**Comment by agherardi** [comment]
Hello - Any updates? Thanks.

**Comment by agherardi** [comment]
Any updates?

**Comment by pavelbucek** [comment]
sorry for the delay, we are quite busy with JAX-RS related tasks.

The updated change looks fine, I've put it into internal pipeline. I expect that it will be merged in a day or so.

Thanks for your contribution!

**Comment by pavelbucek** [comment]
the change has been merged to master and will be rebased to 2.x branch very soon.

**Comment by agherardi** [comment]
Thank you.

**Pull request closed without merging**
