### PR TITLE
Patch for client connection leak when using digest authentication

### PR DESCRIPTION
**Pull request by agherardi**

### CODE REVIEW

**Comment by agherardi** [comment]
OCA http://www.oracle.com/technetwork/community/oca-486395.html

**Comment by agherardi** [comment]
Hello - any updates?

**Comment by agherardi** [comment]
I made an additional change. I noticed that when a server returns 2 WWW-Authenticate headers, the first with Basic the second with Digest, the filter picks Basic even though Digest is stronger and therefore Digest should be used per https://tools.ietf.org/html/rfc2617#section-4.6 . I fixed that issue.

**Comment by pavelbucek** [comment]
@agherardi you could consider posting the other fix as another PR.

Also, there is no test for the other change. And you are using different formatting that the rest of the code..

**Comment by agherardi** [comment]
I'd prefer to keep one PR single the changes are in the same area.

I added unit tests for both changes. i fixed the code formatting issue.

**Comment by pavelbucek** [comment]
I won't. Focused changes do help with the debugging in the future.

Not to mention that the commit message doesn't say anything about the other change.

**Comment by agherardi** [comment]
I can't have 2 pull requests against master at the same time in github. If you either approve or reject https://github.com/jersey/jersey/pull/268, I can submit one change against master and the other against 2.X. Or, I can ask a friend to submit one change on his fork.

Other than that, are you OK with changes + tests?

**Comment by agherardi** [comment]
Any updates? Thanks.

**Comment by agherardi** [comment]
Any updates?

**Comment by agherardi** [comment]
Replaced by https://github.com/jersey/jersey/pull/3751

**Pull request closed without merging**
